#!/usr/bin/env python3
"""Standalone Fig3a family-colored GLMap model map.

This script reads the cached Fig3 coordinates generated by
``scripts/analysis/run_fig3_model_map_embedding.py`` and draws only the
family-colored model-map panel.

Output
------
  figures/Fig3a-model_map_family.pdf

Usage
-----
  $PY scripts/figures/fig3a_model_map_family.py
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.figures.fig3_model_map import (  # noqa: E402
    OTHER_COLOR,
    RCPARAMS,
    _draw_family_map,
    _family_color_map,
    _load_coords,
    _parse_figsize,
)


ANNOTATIONS = {
    "lingxusb/megaDNA": ("megaDNA", 8, 8),
    "lingxusb/PlasmidGPT": ("PlasmidGPT", -26, 10),
    "InstaDeepAI/nucleotide-transformer-2.5b-multi-species": ("NT 2.5B", -28, -12),
    "InstaDeepAI/nucleotide-transformer-v2-500m-multi-species": ("NTv2 500M", 8, -12),
    "InstaDeepAI/NTv3_650M_pre_8kb": ("NTv3 650M 8kb", -46, -2),
    "InstaDeepAI/agro-nucleotide-transformer-1b": ("AgroNT 1B", 8, 10),
    "kuleshov-group/caduceus-ph_seqlen-131k_d_model-256_n_layer-16": (
        "Caduceus 131k", -50, -8,
    ),
    "kuleshov-group/PlantCAD2-Large-l48-d1536": ("PlantCAD2 Large", 8, 10),
    "LongSafari/hyenadna-large-1m-seqlen": ("HyenaDNA 1M", -34, 10),
    "arcinstitute/evo2_40b": ("Evo2 40B", -34, 10),
    "arcinstitute/evo2_40b_base": ("Evo2 40B base", 8, 12),
    "arcinstitute/evo2_7b": ("Evo2 7B", 8, 8),
    "arcinstitute/evo2_1b_base": ("Evo2 1B", 8, 12),
    "evo-design/evo-2-7b-8k-microviridae": ("Evo2 microviridae", -44, -12),
    "GenerTeam/GENERator-v2-eukaryote-3b-base": ("GENERator 3B", -62, 10),
    "DOEJGI/GenomeOcean-4B": ("GenomeOcean 4B", -58, -8),
    "ZhejiangLab/Genos-10B": ("Genos 10B", 8, -14),
    "ZhejiangLab/Genos-1.2B": ("Genos 1.2B", -46, -12),
    "ZhejiangLab/OneGenome-Rice": ("OneGenome Rice", 8, 10),
    "genbio-ai/AIDO.DNA-7B": ("AIDO.DNA 7B", 8, -10),
    "genbio-ai/AIDO.DNA-300M": ("AIDO.DNA 300M", -40, 8),
    "AIRI-Institute/gena-lm-bert-large-t2t": ("GENA-LM large", 8, -14),
    "RaphaelMourad/ModernBERT-DNA-v1-117M-hg38": ("ModernBERT-DNA", 8, 12),
    "JadenLong/MutBERT-Human-Ref": ("MutBERT", 8, -16),
    "RaphaelMourad/Mistral-DNA-v1-138M-noncoding": ("Mistral-DNA noncoding", -82, 8),
    "zhihan1996/DNABERT-2-117M": ("DNABERT-2", -42, -10),
    "zhihan1996/DNABERT-S": ("DNABERT-S", -30, 10),
    "PoetschLab/GROVER": ("GROVER", 8, 12),
    "Mishamq/HybriDNA-7B": ("HybriDNA 7B", 8, 12),
    "living-models/Botanic0-S": ("Botanic0-S", 8, 10),
    "plant-llms/PlantBiMoE": ("PlantBiMoE", 8, -12),
    "GenSLM-2.5B": ("GenSLM 2.5B", 8, 14),
    "Hengchang-Liu/D3LM-from-nt": ("D3LM", 8, -10),
    "togethercomputer/evo-1-131k-base": ("Evo1 131k", 8, -12),
    "HuggingFaceBio/Carbon-8B": ("Carbon 8B", -40, -10),
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--coords", type=Path,
                   default=REPO_ROOT / "out_phase2/model_map/fig3_embedding_Vd_tsne.csv")
    p.add_argument("--out", type=Path,
                   default=REPO_ROOT / "figures/Fig3a-model_map_family.pdf")
    p.add_argument("--family-min-count", type=int, default=4)
    p.add_argument("--figsize", type=str, default="6.3,6.3")
    p.add_argument("--no-annotations", action="store_true",
                   help="Do not label representative checkpoints.")
    return p.parse_args()


def _add_model_annotations(ax, df) -> None:
    by_id = df.set_index("model_id")
    for model_id, (label, dx, dy) in ANNOTATIONS.items():
        if model_id not in by_id.index:
            continue
        row = by_id.loc[model_id]
        ax.annotate(
            label,
            xy=(row["x"], row["y"]),
            xytext=(dx, dy),
            textcoords="offset points",
            fontsize=5.3,
            ha="left" if dx >= 0 else "right",
            va="bottom" if dy >= 0 else "top",
            arrowprops={
                "arrowstyle": "-",
                "color": "#555555",
                "lw": 0.45,
                "shrinkA": 2.0,
                "shrinkB": 2.0,
            },
            bbox={
                "boxstyle": "round,pad=0.15",
                "fc": "white",
                "ec": "none",
                "alpha": 0.72,
            },
            zorder=10,
        )


def main() -> None:
    args = parse_args()
    df = _load_coords(args.coords)
    family_colors, shown_families = _family_color_map(df["family"], args.family_min_count)
    local_rc = {
        **RCPARAMS,
        "font.size": 10.5,
        "axes.labelsize": 10.5,
        "axes.titlesize": 11.5,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 8,
    }
    with plt.rc_context(local_rc):
        fig, ax = plt.subplots(figsize=_parse_figsize(args.figsize), constrained_layout=True)
        _draw_family_map(
            ax, df, family_colors, shown_families,
            title="GLMap model map colored by family", legend=False,
            title_loc="center",
        )
        if not args.no_annotations:
            _add_model_annotations(ax, df)
        ax.set_box_aspect(1)
        ax.text(-0.12, 1.06, "(a)", transform=ax.transAxes,
                fontsize=13, va="top")
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.8)
            spine.set_color("#222")
        counts = Counter(df["family"])
        shown_set = set(shown_families)
        handles = [
            Patch(facecolor=family_colors[f], edgecolor="white", linewidth=0.4,
                  label=f)
            for f in shown_families
        ]
        n_other = int((~df["family"].isin(shown_set)).sum())
        if n_other:
            handles.append(
                Patch(facecolor=OTHER_COLOR, edgecolor="white", linewidth=0.4,
                      label="Other")
            )
        ax.legend(
            handles=handles,
            frameon=True,
            fontsize=7,
            loc="upper right",
            bbox_to_anchor=(0.988, 0.988),
            ncol=2,
            handlelength=0.75,
            handletextpad=0.30,
            columnspacing=0.55,
            labelspacing=0.14,
            borderpad=0.22,
            framealpha=0.80,
            facecolor="white",
            edgecolor="#D0D0D0",
        )
        args.out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.out, dpi=300)
        plt.close(fig)
    print(f"[done] wrote {args.out.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
