#!/usr/bin/env python3
"""Standalone Fig3c GLMap model map colored by 6-TaskMean.

This script reads the cached Fig3 coordinates generated by
``scripts/analysis/run_fig3_model_map_embedding.py`` and draws the same
model map with a continuous color overlay for mean downstream AUC across
the six benchmark tasks.

Output
------
  figures/Fig3c-model_map_6task_mean.pdf

Usage
-----
  $PY scripts/figures/fig3c_model_map_6task_mean.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.figures.fig3_model_map import (  # noqa: E402
    RCPARAMS,
    _load_coords,
    _parse_figsize,
    _polish_map_axis,
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--coords", type=Path,
                   default=REPO_ROOT / "out_phase2/model_map/fig3_embedding_Vd_tsne.csv")
    p.add_argument("--out", type=Path,
                   default=REPO_ROOT / "figures/Fig3c-model_map_6task_mean.pdf")
    p.add_argument("--figsize", type=str, default="6.3,6.3")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    df = _load_coords(args.coords)
    local_rc = {
        **RCPARAMS,
        "font.size": 10.5,
        "axes.labelsize": 10.5,
        "axes.titlesize": 11.5,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 8,
    }
    with plt.rc_context(local_rc):
        fig, ax = plt.subplots(figsize=_parse_figsize(args.figsize), constrained_layout=True)
        sc = ax.scatter(
            df["x"], df["y"], c=df["mean_auc"],
            cmap="viridis", s=30, alpha=0.92,
            edgecolors="white", linewidths=0.45,
            vmin=float(df["mean_auc"].quantile(0.02)),
            vmax=float(df["mean_auc"].quantile(0.98)),
            rasterized=True,
        )
        ax.set_title("GLMap model map colored by 6-TaskMean", loc="center", pad=8)
        _polish_map_axis(ax, df)
        ax.set_box_aspect(1)
        ax.text(-0.12, 1.06, "(c)", transform=ax.transAxes,
                fontsize=13, va="top")
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.8)
            spine.set_color("#222")
        cbar = fig.colorbar(sc, ax=ax, fraction=0.046, pad=0.025)
        cbar.outline.set_linewidth(0.6)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.out, dpi=300)
        plt.close(fig)
    print(f"[done] wrote {args.out.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
