#!/usr/bin/env python3
"""Figure 2 (preview): gLM-perspective model-level structure.

For each branch (AR / MLM), runs PCA on the Q matrix (M models × N probes,
double-centered) to project MODELS into a 2D probe space. Models that
perceive the panel similarly cluster; the spectrum reveals families.

Inputs (regenerated by run_phase1_scoring.py --from-audit [--allow-missing]):
  out_phase1/matrices/Q_AR.npy
  out_phase1/matrices/Q_MLM.npy
  out_phase1/matrices/scored_models_actual.json  (for ordered model_ids)

Output (regenerable, not git-tracked):
  figures/model_q_pca.{pdf,png}
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.figures.phase1_main_figure import PALETTE, RCPARAMS  # noqa: E402


# ─────────────────────── family classification ───────────────────────

# Broad families used for coloring. Each model maps to exactly one family
# via the first matching pattern. Order matters (more specific before
# less specific). Colors are assigned from PALETTE so the figure stays
# in the repo's publication style.
FAMILY_RULES: list[tuple[str, str, str]] = [
    # (substring matcher, family label, color)
    ("arcinstitute/evo2",                 "evo2",          PALETTE["blue_main"]),
    ("evo-design/evo-2",                  "evo2",          PALETTE["blue_main"]),
    ("togethercomputer/evo-1",            "evo-1",         PALETTE["blue_secondary"]),
    ("LongSafari/evo-1",                  "evo-1",         PALETTE["blue_secondary"]),
    ("evo-design/evo-1",                  "evo-1",         PALETTE["blue_secondary"]),
    ("GenerTeam/GENERator",               "GENERator",     PALETTE["violet"]),
    ("GenerTeam/GENERanno",               "GENERanno",     PALETTE["green_3"]),
    ("GenSLM",                            "GenSLM",        PALETTE["red_strong"]),
    ("LongSafari/hyenadna",               "HyenaDNA",      PALETTE["teal"]),
    ("InstaDeepAI/NTv3",                  "NTv3",          PALETTE["red_secondary"]),
    ("InstaDeepAI/nucleotide-transformer","NT v1/v2",      PALETTE["red_light"]),
    ("InstaDeepAI/agro-nucleotide",       "NT v1/v2",      PALETTE["red_light"]),
    ("zhihan1996/DNABERT",                "DNABERT",       PALETTE["highlight"]),
    ("kuleshov-group/caduceus",           "Caduceus",      "#A2D9A5"),
    ("kuleshov-group/PlantCAD",           "PlantCAD",      "#D4F0D6"),
    ("AIRI-Institute/gena-lm",            "GENA-LM",       "#FFA94D"),
    ("AIRI-Institute/moderngena",         "GENA-LM",       "#FFA94D"),
    ("DOEJGI/GenomeOcean",                "GenomeOcean",   "#22B8CF"),
    ("ZhejiangLab/Genos",                 "Genos",         "#8B4513"),
    ("ZhejiangLab/OneGenome",             "Genos",         "#8B4513"),
    ("genbio-ai/AIDO",                    "AIDO",          "#C77DFF"),
    ("RaphaelMourad/Mistral-DNA",         "Mistral-DNA",   "#FF6FAF"),
    ("RaphaelMourad/ModernBERT",          "ModernBERT-DNA","#D946EF"),
    ("RaphaelMourad/ModernBert",          "ModernBERT-DNA","#D946EF"),
    ("RaphaelMourad/Jamba",               "Jamba-DNA",     "#94A3B8"),
    ("Mishamq/HybriDNA",                  "HybriDNA",      "#4ADE80"),
    ("JadenLong/MutBERT",                 "MutBERT",       "#F472B6"),
    ("living-models/Botanic",             "Botanic0",      "#84CC16"),
    ("plant-llms/PlantBiMoE",             "PlantBiMoE",    "#10B981"),
    ("lingxusb/megaDNA",                  "megaDNA",       "#FB923C"),
    ("lingxusb/PlasmidGPT",               "PlasmidGPT",    "#A8A29E"),
    ("Hengchang-Liu/D3LM",                "D3LM",          "#0EA5E9"),
    ("HuggingFaceBio/Carbon",              "Carbon",        "#7C3AED"),
]

OTHER_COLOR = PALETTE["neutral"]
OTHER_LABEL = "Other"


def _classify_family(hf_id: str) -> tuple[str, str]:
    for pattern, label, color in FAMILY_RULES:
        if pattern in hf_id:
            return label, color
    return OTHER_LABEL, OTHER_COLOR


def _short_name(hf_id: str) -> str:
    """Last path component, truncated for inline labels."""
    name = hf_id.split("/")[-1]
    # Remove the most verbose suffixes for layout
    for kill in ("-multi-species", "-1000g", "-human-ref", "-Ref", "-base"):
        if name.endswith(kill):
            name = name[: -len(kill)]
    return name[:24]


# ─────────────────────── data loading ────────────────────────


def _load_branch(matrices_dir: Path, branch: str) -> tuple[np.ndarray, list[str]]:
    """Load Q_{branch}.npy + the model_ids for that branch."""
    Q = np.load(matrices_dir / f"Q_{branch.upper()}.npy")
    actual = json.loads((matrices_dir / "scored_models_actual.json").read_text())
    model_ids = actual[branch.lower()]["scored_models"]
    if Q.shape[0] != len(model_ids):
        raise ValueError(
            f"Q_{branch} has {Q.shape[0]} rows but scored_models_actual.json "
            f"lists {len(model_ids)} {branch} models"
        )
    return Q, model_ids


def _run_pca(Q: np.ndarray, seed: int = 42) -> tuple[np.ndarray, np.ndarray]:
    """PCA on the rows (models) of Q. Returns (embedding, ev_ratio_top2)."""
    from sklearn.decomposition import PCA
    pca = PCA(n_components=2, random_state=seed)
    embed = pca.fit_transform(Q)
    return embed, pca.explained_variance_ratio_


def _run_tsne_modelmap(Q: np.ndarray, seed: int = 42) -> np.ndarray:
    """t-SNE on Q rows using the ModelMap (1000-models paper) exact recipe.

    Reference:
      /nvme-data3/yusen/worksapce/glm_mapping/modelmap/resampling-texts/tsne_Q.py
      TSNE(n_components=2, perplexity=30, max_iter=10000,
           init='pca', metric='sqeuclidean', random_state=42)

    metric='sqeuclidean' is the key choice — squared Euclidean on Q
    is the small-divergence Taylor approximation of pairwise KL between
    models (ModelMap §6.1).
    """
    from sklearn.manifold import TSNE
    tsne = TSNE(
        n_components=2, perplexity=30, max_iter=10000,
        init="pca", metric="sqeuclidean", random_state=seed, verbose=0,
    )
    return tsne.fit_transform(Q)


# ─────────────────────── one panel ────────────────────────


def _draw_branch(ax, Q: np.ndarray, model_ids: list[str], branch_label: str,
                  projection: str = "tsne",
                  annotate_outliers: bool = True) -> None:
    if projection == "tsne":
        embed = _run_tsne_modelmap(Q)
        ev = None
    elif projection == "pca":
        embed, ev = _run_pca(Q)
    else:
        raise ValueError(f"unknown projection={projection!r}")
    # Group by family for legend grouping (color order in legend matches
    # row order of first appearance in model_ids).
    families: dict[str, tuple[str, list[int]]] = {}
    for i, hf_id in enumerate(model_ids):
        fam, color = _classify_family(hf_id)
        if fam not in families:
            families[fam] = (color, [])
        families[fam][1].append(i)

    for fam, (color, idxs) in families.items():
        idxs_arr = np.asarray(idxs)
        ax.scatter(
            embed[idxs_arr, 0], embed[idxs_arr, 1],
            c=color, s=85, alpha=0.85,
            edgecolors="black", linewidths=0.5,
            label=f"{fam} (n={len(idxs)})",
        )

    # Annotate the 3 most extreme outliers on each axis (likely
    # fine-tuned-narrow or distribution-shifted models)
    if annotate_outliers:
        pc1 = embed[:, 0]
        pc2 = embed[:, 1]
        extremes = set()
        # 4 corners + 2 axis extremes
        for ranking in (np.argsort(pc1)[:2], np.argsort(pc1)[-2:],
                        np.argsort(pc2)[:2], np.argsort(pc2)[-2:]):
            extremes.update(ranking.tolist())
        for i in extremes:
            ax.annotate(
                _short_name(model_ids[i]),
                (embed[i, 0], embed[i, 1]),
                fontsize=7, color="#222",
                xytext=(4, 4), textcoords="offset points",
                alpha=0.85,
            )

    if projection == "pca":
        ax.set_xlabel(f"PC1 ({ev[0]*100:.1f}%)")
        ax.set_ylabel(f"PC2 ({ev[1]*100:.1f}%)")
    else:
        ax.set_xlabel("t-SNE 1")
        ax.set_ylabel("t-SNE 2")
    ax.set_title(
        f"{branch_label} branch — {Q.shape[0]} models × {Q.shape[1]} probes",
        loc="left", fontweight="bold",
    )
    leg = ax.legend(
        loc="center left", bbox_to_anchor=(1.01, 0.5),
        fontsize=8, handlelength=1.2, borderaxespad=0.3,
        labelspacing=0.55,
    )


def _draw_combined(ax, Q_combined: np.ndarray, model_ids: list[str],
                    branch_labels: list[str], projection: str = "tsne",
                    annotate_outliers: bool = True) -> None:
    """Single panel showing AR + MLM models together. AR is marker='o',
    MLM is marker='^'. Each branch was already per-branch std-normalized
    by the caller before concatenation."""
    if projection == "tsne":
        embed = _run_tsne_modelmap(Q_combined)
        ev = None
    elif projection == "pca":
        embed, ev = _run_pca(Q_combined)
    else:
        raise ValueError(f"unknown projection={projection!r}")

    # Group by (family, branch) so the legend can render family-by-family,
    # with marker shape encoding branch.
    BRANCH_MARKER = {"ar": "o", "mlm": "^"}
    families_seen: list[tuple[str, str]] = []   # (label, color), legend order
    family_branch_idx: dict[tuple[str, str], list[int]] = {}
    for i, (hf_id, branch) in enumerate(zip(model_ids, branch_labels)):
        fam, color = _classify_family(hf_id)
        if (fam, color) not in families_seen:
            families_seen.append((fam, color))
        family_branch_idx.setdefault((fam, branch), []).append(i)

    for fam, color in families_seen:
        n_ar = len(family_branch_idx.get((fam, "ar"), []))
        n_mlm = len(family_branch_idx.get((fam, "mlm"), []))
        # Decide which branch's scatter call carries the family-color legend
        # entry: whichever branch has at least one model. Prefer AR if both.
        legend_branch = "ar" if n_ar > 0 else "mlm"
        if n_ar > 0 and n_mlm > 0:
            family_label = f"{fam} (AR={n_ar}, MLM={n_mlm})"
        elif n_ar > 0:
            family_label = f"{fam} (AR×{n_ar})"
        else:
            family_label = f"{fam} (MLM×{n_mlm})"
        for branch in ("ar", "mlm"):
            idxs = family_branch_idx.get((fam, branch), [])
            if not idxs:
                continue
            idxs_arr = np.asarray(idxs)
            ax.scatter(
                embed[idxs_arr, 0], embed[idxs_arr, 1],
                c=color, s=90, alpha=0.85,
                marker=BRANCH_MARKER[branch],
                edgecolors="black", linewidths=0.5,
                label=family_label if branch == legend_branch else None,
            )

    # Outlier annotations on the combined embedding
    if annotate_outliers:
        pc1, pc2 = embed[:, 0], embed[:, 1]
        extremes = set()
        for ranking in (np.argsort(pc1)[:3], np.argsort(pc1)[-3:],
                        np.argsort(pc2)[:3], np.argsort(pc2)[-3:]):
            extremes.update(ranking.tolist())
        for i in extremes:
            ax.annotate(
                _short_name(model_ids[i]),
                (embed[i, 0], embed[i, 1]),
                fontsize=7, color="#222",
                xytext=(4, 4), textcoords="offset points", alpha=0.85,
            )

    if projection == "pca":
        ax.set_xlabel(f"PC1 ({ev[0]*100:.1f}%)")
        ax.set_ylabel(f"PC2 ({ev[1]*100:.1f}%)")
    else:
        ax.set_xlabel("t-SNE 1")
        ax.set_ylabel("t-SNE 2")
    n_ar = sum(1 for b in branch_labels if b == "ar")
    n_mlm = sum(1 for b in branch_labels if b == "mlm")
    ax.set_title(
        f"Combined AR + MLM — {n_ar} AR + {n_mlm} MLM = "
        f"{len(model_ids)} models × {Q_combined.shape[1]} probes",
        loc="left", fontweight="bold",
    )

    # Two legends: family colors on the right, branch markers in-axes
    leg1 = ax.legend(
        loc="center left", bbox_to_anchor=(1.01, 0.5),
        fontsize=8, handlelength=1.2, borderaxespad=0.3,
        labelspacing=0.55, title="Family", title_fontsize=9,
    )
    ax.add_artist(leg1)
    # Manual handles for branch marker legend
    ar_h = ax.scatter([], [], c="#888", s=80, marker="o",
                       edgecolors="black", linewidths=0.5, label="AR (forward log p)")
    mlm_h = ax.scatter([], [], c="#888", s=80, marker="^",
                        edgecolors="black", linewidths=0.5, label="MLM (stride PLL)")
    ax.legend(
        handles=[ar_h, mlm_h],
        loc="lower left", fontsize=8, frameon=True,
        title="Branch", title_fontsize=9,
    )


# ─────────────────────── main ────────────────────────


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--matrices-dir", type=Path,
                   default=REPO_ROOT / "out_phase1" / "matrices",
                   help="Directory holding Q_{AR,MLM}.npy + "
                        "scored_models_actual.json.")
    p.add_argument("--out-dir", type=Path, default=REPO_ROOT / "figures",
                   help="Output directory for the figure.")
    p.add_argument("--basename", type=str, default="model_map",
                   help="Basename (no extension) for the figure. The chosen "
                        "projection is appended as a suffix.")
    p.add_argument("--projection", type=str, default="tsne",
                   choices=["tsne", "pca"],
                   help="2D projection of Q rows. 'tsne' (default) uses the "
                        "ModelMap (1000-models paper) recipe: perplexity=30, "
                        "max_iter=10000, init=pca, metric=sqeuclidean, "
                        "seed=42. sqeuclidean is the small-divergence Taylor "
                        "approximation of pairwise KL between models "
                        "(ModelMap §6.1). 'pca' is the linear baseline; PC1 "
                        "tends to be dominated by row-norm outliers (e.g. "
                        "narrow-trained models with extreme Q-vector "
                        "magnitudes).")
    p.add_argument("--combine-branches", action="store_true",
                   help="Project AR and MLM models together into a single 2D "
                        "layout. Each branch is rescaled to unit std before "
                        "concat so the heavier MLM PLL magnitudes don't "
                        "dominate distances. AR / MLM are distinguished by "
                        "marker shape (circle vs triangle). NOTE: phase_1.md "
                        "protocol forbids cross-branch quantitative analysis "
                        "(log p(x) vs PLL(x) are different probability "
                        "objects); this combined view is for exploratory "
                        "visualization only.")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if not (args.matrices_dir / "Q_AR.npy").exists():
        sys.exit(f"Q_AR.npy not found in {args.matrices_dir}; run aggregate first")

    Q_ar, ids_ar = _load_branch(args.matrices_dir, "ar")
    Q_mlm, ids_mlm = _load_branch(args.matrices_dir, "mlm")

    print(f"[model_map] AR  Q: {Q_ar.shape}  (std={Q_ar.std():.2f})", flush=True)
    print(f"[model_map] MLM Q: {Q_mlm.shape}  (std={Q_mlm.std():.2f})", flush=True)

    with plt.rc_context(RCPARAMS):
        if args.combine_branches:
            # Per-branch std normalization, then concat
            Q_ar_n = Q_ar / Q_ar.std()
            Q_mlm_n = Q_mlm / Q_mlm.std()
            Q_combined = np.concatenate([Q_ar_n, Q_mlm_n], axis=0)
            ids_combined = list(ids_ar) + list(ids_mlm)
            branch_labels = ["ar"] * len(ids_ar) + ["mlm"] * len(ids_mlm)
            print(f"[model_map] combined Q: {Q_combined.shape}  "
                  f"(branches std-normalized to 1)", flush=True)

            fig = plt.figure(figsize=(13, 9))
            gs = fig.add_gridspec(
                1, 1,
                left=0.07, right=0.78, top=0.92, bottom=0.08,
            )
            ax = fig.add_subplot(gs[0, 0])
            _draw_combined(ax, Q_combined, ids_combined, branch_labels,
                            projection=args.projection)
            proj_long = {"tsne": "t-SNE (ModelMap recipe)", "pca": "PCA"}[args.projection]
            fig.suptitle(
                f"Figure 2 (preview): gLM-perspective model structure — "
                f"{proj_long}, AR + MLM combined (per-branch std-normalized)",
                fontsize=11.5, fontweight="bold", y=0.97,
            )
            suffix = f"{args.projection}_combined"
        else:
            fig = plt.figure(figsize=(16, 7))
            gs = fig.add_gridspec(
                1, 2, wspace=0.55,
                left=0.06, right=0.85, top=0.90, bottom=0.10,
            )
            ax_a = fig.add_subplot(gs[0, 0])
            _draw_branch(ax_a, Q_ar, ids_ar, "(a) AR", projection=args.projection)
            ax_b = fig.add_subplot(gs[0, 1])
            _draw_branch(ax_b, Q_mlm, ids_mlm, "(b) MLM", projection=args.projection)
            proj_long = {"tsne": "t-SNE (ModelMap recipe)", "pca": "PCA"}[args.projection]
            fig.suptitle(
                f"Figure 2 (preview): gLM-perspective model structure — "
                f"{proj_long} on Q matrix rows in probe space",
                fontsize=12, fontweight="bold", y=0.985,
            )
            suffix = args.projection

        args.out_dir.mkdir(parents=True, exist_ok=True)
        for ext in ("pdf", "png"):
            path = args.out_dir / f"{args.basename}_{suffix}.{ext}"
            fig.savefig(path, dpi=300, bbox_inches="tight", pad_inches=0.08)
            print(f"[done] wrote {path}", flush=True)
        plt.close(fig)


if __name__ == "__main__":
    main()
